-- 11월 24일 오늘의 SQL
SELECT * 
FROM EMP
WHERE JOB != 'MANAGER'
AND JOB <> 'SALESMAN'
AND JOB ^= 'CLERK';

SELECT *
FROM EMP
WHERE JOB NOT IN ('MANAGER','SALESMAN','CLERK');

SELECT *
FROM EMP
WHERE SAL >= 2000
AND SAL <= 3000;

SELECT *
FROM EMP
WHERE SAL BETWEEN 2000 AND 3000;

SELECT * 
FROM EMP
WHERE SAL NOT BETWEEN 2000 AND 3000;

SELECT *
FROM EMP
WHERE ENAME LIKE 'S%';

SELECT *
FROM EMP
WHERE ENAME LIKE '_L%';

SELECT *
FROM EMP
WHERE ENAME LIKE '%AM%';

SELECT *
FROM EMP
WHERE ENAME NOT LIKE '%AM%';

SELECT ENAME SAL, SAL*12+COMM AS ANNSAL, COMM
FROM EMP;

SELECT *
FROM EMP
WHERE COMM = NULL;

SELECT *
FROM EMP
WHERE COMM IS NULL;

SELECT *
FROM EMP
WHERE SAL > NULL
AND COMM IS NULL;

SELECT *
FROM EMP
WHERE SAL > NULL
OR COMM IS NULL;

SELECT EMPNO, ENAME,SAL DEPTNO
FROM EMP
WHERE DEPTNO = 20;

SELECT EMPNO,ENAME,SAL,DEPTNO
FROM EMP
WHERE DEPTNO = 10
UNION
SELECT EMPNO,ENAME,SAL,DEPTNO
FROM EMP
WHERE DEPTNO = 20;

SELECT EMPNO,ENAME,SAL,DEPTNO
FROM EMP
WHERE DEPTNO IN (10,20);

SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24:MI:SS') AS 현재날짜시간
FROM DUAL;

SELECT SYSDATE,
TO_CHAR(SYSDATE, 'MM') AS MM,
TO_CHAR(SYSDATE, 'MON') AS MON,
TO_CHAR(SYSDATE, 'MONTH') AS MONTH,
TO_CHAR(SYSDATE, 'DD') AS DD,
TO_CHAR(SYSDATE, 'DY') AS DY,
TO_CHAR(SYSDATE, 'DAY') AS DAY
FROM DUAL;

SELECT SYSDATE,
TO_CHAR(SYSDATE,'HH24:MI:SS') AS HH24MISS,
TO_CHAR(SYSDATE,'HH12:MI:SS') AS HHMISS_AM,
TO_CHAR(SYSDATE,'HH:MI:SS P.M') AS HHMISS_PM
FROM DUAL;

SELECT 1300 - '1500',
       '1500' + 1500
       FROM DUAL;
       

SELECT EMPNO,
       ENAME,
       SAL,
       COMM,
       SAL + COMM,
       NVL (COMM, 0),
       SAL + NVL (COMM, 0)
  FROM EMP;
  
  SELECT EMPNO,
       ENAME,
       COMM,
       NVL2 (COMM, '0', 'X'),
       NVL2 (COMM, SAL * 12 + COMM, SAL * 12)     AS ANNSAL
  FROM EMP;
  

SELECT EMPNO,
       ENAME,
       JOB,
       SAL,
       DECODE (JOB,
               'MANAGER', SAL * 1.1,
               'SALESMAN', SAL * 1.05,
               'ANALYST', SAL,
               SAL * 1.03)    AS UPSAL
  FROM EMP;
  
  
SELECT EMPNO,
       ENAME,
       JOB,
       SAL,
       DECODE (JOB,
               'MANAGER', SAL * 1.1,
               'SALESMAN', SAL * 1.05,
               'ANALYST', SAL,
               SAL * 1.03)    AS UPSAL
  FROM EMP;
  
  
  SELECT EMPNO,
       ENAME,
       JOB,
       SAL,
       CASE JOB
           WHEN 'MANAGER' THEN SAL * 1.1
           WHEN 'SALESMAN' THEN SAL * 1.05
           WHEN 'ANALYST' THEN SAL
           ELSE SAL * 1.03
       END    AS UPSAL
  FROM EMP;
  
  
SELECT EMPNO,
       ENAME,
       COMM,
       CASE
           WHEN COMM IS NULL THEN '해당사항 없음'
           WHEN COMM = 0 THEN '수당없음'
           WHEN COMM > 0 THEN '수당 : ' || COMM
       END    AS COMM_TEXT
  FROM EMP;
  
  SELECT SUM(SAL)
  FROM EMP;
  
  SELECT ENAME, SUM(SAL)
  FROM EMP;  -- 오류
  
 
    SELECT SUM(COMM)
    FROM EMP;
    
SELECT SUM (DISTINCT SAL), SUM (ALL SAL), SUM (SAL) FROM EMP;

SELECT COUNT (*) FROM EMP;

SELECT COUNT (*)
  FROM EMP
 WHERE DEPTNO = 30;
 
SELECT COUNT (DISTINCT SAL), COUNT (ALL SAL), COUNT (SAL) FROM EMP;


 SELECT COUNT (COMM)
 FROM EMP;
 
 SELECT COUNT(COMM)
 FROM EMP
 WHERE COMM IS NOT NULL;
 
 SELECT MAX(SAL)
 FROM EMP
 WHERE DEPTNO = 10;
 
 SELECT MIN(SAL)
 FROM EMP
 WHERE DEPTNO = 10;
 
 SELECT MAX(HIREDATE)
 FROM EMP
 WHERE DEPTNO = 20;
 
 SELECT MIN(HIREDATE)
 FROM EMP
 WHERE DEPTNO = 20;
 
 SELECT AVG(SAL)
    FROM EMP 
    WHERE DEPTNO =30;
    
    SELECT AVG(DISTINCT SAL)
    FROM EMP
    WHERE DEPTNO = 30;
    
    SELECT AVG(SAL), DEPTNO
    FROM EMP
    GROUP BY DEPTNO;
    
    SELECT DEPTNO, JOB , AVG(SAL)
    FROM EMP
    GROUP BY DEPTNO, JOB
    ORDER BY DEPTNO, JOB;
    
    SELECT DEPTNO, JOB, AVG(SAL)
    FROM EMP
    GROUP BY DEPTNO, JOB
    HAVING AVG(SAL) >= 2000
    ORDER BY DEPTNO, JOB;
    
    SELECT DEPTNO,JOB,AVG(SAL)
    FROM EMP
    GROUP BY DEPTNO, JOB
    HAVING AVG(SAL) >= 2000
    ORDER BY DEPTNO, JOB;
   

  SELECT DEPTNO, JOB, SAL
    FROM EMP
   WHERE SAL <= 3000
ORDER BY DEPTNO, JOB;

    SELECT * 
    FROM EMP,DEPT
    ORDER BY EMPNO;
    
    SELECT EMPNO,ENAME,DEPTNO,DNAME,LOC
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO;
    
    SELECT E.EMPNO, E.ENAME, D.DNAME,D.LOC
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
    ORDER BY D.DEPTNO,E.EMPNO;
    
    SELECT E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.LOC
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
    AND SAL >= 3000;
    
    SELECT * FROM EMP;
    
    SELECT * FROM SALGRADE;
    
    SELECT * FROM EMP E, SALGRADE S 
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;
    
    SELECT E1.EMPNO, E1.ENAME, E1.MGR,
            E2.EMPNO AS MGR_EMPNO,
            E2.ENAME AS MGR_ENAME
            FROM EMP E1, EMP E2
            WHERE E1.MGR = E2.EMPNO;
            
            
    SELECT E1.EMPNO, E1.ENAME, E1.MGR,
           E2.EMPNO AS MGR_EMPNO,
           E2.ENAME AS MGR_ENAME
           FROM EMP E1, EMP E2
           WHERE E1.MGR = E2.EMPNO(+)
           ORDER BY E1.EMPNO;
           
    SELECT E1.EMPNO,E2.ENAME,E1.MGR,
           E2.EMPNO AS MGR_EMPNO,
           E2.ENAME AS MGR_ENAME
           FROM EMP E1, EMP E2
           WHERE E1.MGR(+) = E2.EMPNO
           ORDER BY E1.EMPNO;
           
    SELECT E.EMPNO, E.ENAME,E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM,
    DEPTNO, D.DNAME, D.LOC
    FROM EMP E NATURAL JOIN DEPT D
    ORDER BY DEPTNO, E.EMPNO;
    

SELECT *
FROM EMP
WHERE DEPTNO IN (20, 30);

SELECT *
  FROM EMP
 WHERE SAL IN (  SELECT MAX (SAL)
                   FROM EMP
               GROUP BY DEPTNO);
               
SELECT MAX(SAL)
FROM EMP
GROUP BY DEPTNO;

SELECT *
FROM EMP
WHERE SAL = ANY (SELECT MAX(SAL)
                FROM EMP
                GROUP BY DEPTNO);
                
SELECT *
FROM EMP
WHERE SAL = SOME(SELECT MAX(SAL)
                 FROM EMP
                 GROUP BY DEPTNO);
                 
                 
                 
SELECT * FROM EMP
WHERE SAL < ANY (SELECT SAL FROM EMP WHERE DEPTNO = 30)
ORDER BY SAL, EMPNO;

SELECT SAL
FROM EMP
WHERE DEPTNO =30;

SELECT *
FROM EMP
WHERE SAL > ANY ( SELECT SAL 
                    FROM EMP
                    WHERE DEPTNO = 30);
                    
SELECT SAL
FROM EMP
WHERE DEPTNO = 30;

SELECT *
FROM EMP
WHERE SAL > ANY (SELECT SAL
                FROM EMP
                WHERE DEPTNO = 30);
               

SELECT SAL 
FROM EMP
WHERE DEPTNO = 30;


SELECT * 
FROM EMP
WHERE SAL < ALL (SELECT SAL
                 FROM EMP
                 WHERE DEPTNO = 30);

SELECT *
  FROM EMP
 WHERE SAL > ALL (SELECT SAL
                    FROM EMP
                   WHERE DEPTNO = 30);