CREATE TABLE EMP_DDL(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    MGR NUMBER(4),
    HIREDATE DATE,
    SAL NUMBER(7,2),
    COMM NUMBER(7,2),
    DEPTNO NUMBER(2)
);

DESC EMP_DDL;

CREATE TABLE DEPT_DDL
AS SELECT * FROM DEPT;
    
    
DESC DEPT_DDL;
--테이블 전체 조회하기    
SELECT * FROM DEPT_DDL;

-- 다른 테이블의 일부를 복사하여 테이블 생성하기
CREATE TABLE EMP_DDL_30
AS SELECT *
FROM EMP
WHERE DEPTNO = 30;

SELECT * FROM EMP_DDL_30;

--기존 테이블의 열 구조만 복사하여 새 테이블 생성하기

CREATE TABLE EMPDEPT_DDL
AS SELECT E.EMPNO,E.ENAME,E.JOB,E.MGR,E.HIREDATE,
E.SAL,E.COMM,D.DEPTNO,D.DNAME,D.LOC
FROM EMP E, DEPT D
WHERE 1<> 1;

SELECT * FROM EMPDEPT_DDL;

CREATE TABLE EMP_ALTER
    AS SELECT * FROM EMP;
    
    SELECT * FROM EMP_ALTER;

--ALTER명령어로 HP 열 추가하기
    
ALTER TABLE EMP_ALTER
ADD HP VARCHAR2(20);

SELECT * FROM EMP_ALTER;

--ALTER 명령어로 HP 열 이름을 TEL로 변경하기

ALTER TABLE EMP_ALTER
 RENAME COLUMN HP TO TEL;

SELECT * FROM EMP_ALTER; 

--ALTER 명령어로 EMPNO 열 길이 변경하기

ALTER TABLE EMP_ALTER
MODIFY EMPNO NUMBER(5);

DESC EMP_ALTER;

--특정 열을 삭제할 때 사용하는 DROP
ALTER TABLE EMP_ALTER
DROP COLUMN TEL;

SELECT * FROM EMP_ALTER;


--테이블 이름 변경하기

RENAME EMP_ALTER TO EMP_RENAME;

SELECT *
FROM EMP_RENAME;

--EMP_RENAME 테이블의 전체 데이터 삭제하기

TRUNCATE TABLE EMP_RENAME;

SELECT * FROM EMP_RENAME;

-- 이 명령어는 롤백이 불가능합니다. 즉 삭제 이후에 복구가 불가능합니다.

--테이블 삭제하는 DROP
DROP TABLE EMP_RENAME;

DESC EMP_RENAME;

