--조인
--FROM절에 여러 테이블 선언하기
SELECT * FROM EMP, DEPT
ORDER BY EMPNO;

-- 열 이름을 비교하는 조건식으로 조인하기
SELECT *
FROM EMP,DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
ORDER BY EMPNO;

--테이블 이름을 별칭으로 표현하기

SELECT *
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
ORDER BY EMPNO;

SELECT E.EMPNO, E.ENAME, E.JOB,E.MGR,E.HIREDATE,E.SAL,E.COMM,E.DEPTNO,
D.DNAME,D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
ORDER BY EMPNO;

SELECT EMPNO,ENAME,DEPTNO,DNAME,LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
ORDER BY EMPNO;

-- 열 이름에 각각의 테이블 이름도 함께 명시할 때
SELECT E.EMPNO, E.ENAME,D.DEPTNO,D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
ORDER BY D.DEPTNO, E.EMPNO;

-- WHERE절에 추가로 조건식 넣어 출력하기

SELECT E.EMPNO,E.ENAME,E.SAL,D.DEPTNO,D.DNAME,D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND SAL >= 3000;
--예제
SELECT E.EMPNO, E.ENAME,E.SAL,D.DEPTNO,D.DNAME,D.LOC
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
AND E.SAL <= 2500
AND E.EMPNO <= 9999
ORDER BY E.EMPNO;

--비등가 조인
SELECT * FROM EMP;
SELECT * FROM SALGRADE;
--급여 범위를 지정하는 조건식으로 조인하기
SELECT *
FROM EMP E, SALGRADE S 
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;


--같은 테이블을 두 번 사용하여 자체 조인하기

SELECT E1.EMPNO, E1.ENAME,E1.MGR,
E2.EMPNO AS MGR_EMPNO,
E2.ENAME AS MGR_ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO;

--왼쪽 외부 조인 사용하기
SELECT E1.EMPNO, E1.ENAME, E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO(+)
ORDER BY E1.EMPNO;


--오른쪽 외부 조인 사용하기

SELECT E1.EMPNO, E1.ENAME,E1.MGR,
       E2.EMPNO AS MGR_EMPNO,
       E2.ENAME AS MGR_ENAME
FROM EMP E1, EMP E2
WHERE E1.MGR(+) = E2.EMPNO
ORDER BY E1.EMPNO;


--SQL-99 표준 문법으로 배우는 조인,NATURAL JOIN

SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE,E.SAL,E.COMM,
       DEPTNO, D.DNAME, D.LOC
       FROM EMP E NATURAL JOIN DEPT D
       ORDER BY DEPTNO, E.EMPNO;
       
--JOIN ~ USING을 사용하여 조인하기

SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM,
        DEPTNO, D.DNAME, D.LOC
        FROM EMP E JOIN DEPT D USING (DEPTNO)
        WHERE SAL >= 3000
        ORDER BY DEPTNO, E.EMPNO;
        
--JOIN ON으로 등가 조인하기
SELECT E.EMPNO, E.JOB,E.HIREDATE,E.SAL,E.COMM,
        E.DEPTNO,
        D.DNAME,D.LOC
        FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
        WHERE SAL <=3000
        ORDER BY E.DEPTNO, EMPNO;
        
 -- 왼쪽 외부 조인을 SQL-99로 작성하기
 
 SELECT E1.EMPNO, E1.ENAME,E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME
        FROM EMP E1 LEFT OUTER JOIN EMP E2 ON(E1.MGR = E2.MGR)
        ORDER BY E1.EMPNO;
        
 -- 오른쪽 외부 조인을 SQL_99로 작성하기
 
 SELECT E1.EMPNO, E1.ENAME,E1.MGR,
        E2.EMPNO AS MGR_EMPNO,
        E2.ENAME AS MGR_ENAME        
        FROM EMP E1 RIGHT OUTER JOIN EMP E2 ON (E1.MGR = E2.MGR)
        ORDER BY E1.EMPNO,MGR_EMPNO;
 
--SQL-99 조인 방식에서 세 개 이상의 테이블을 조인할 때
--FROM TABLE1, TABLE2, TABLE3
--WHERE TABLE1.COL = TABLE2.COL
--AND TABLE2.COL = TABLE3.COL

--FROM TABLE1 JOIN TALBE2 ON (조건식)
--JOIN TABLE3 ON (조건식)