--DEPT 테이블을 복사해서 DEPT_TCL 테이블 만들기
CREATE TABLE DEPT_TCL
    AS SELECT *
        FROM DEPT;
        --조회
        SELECT * FROM DEPT_TCL;

--DEPT_TCL 테이블에 데이터 입력 수정 삭제하기

INSERT INTO DEPT_TCL VALUES(50,'DATABASE','SEOUL');

UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 40; 

DELETE FROM DEPT_TCL WHERE DNAME = 'RESEARCH';

SELECT * FROM DEPT_TCL;

--롤백으로 명령어 실행 취소하기

ROLLBACK;
SELECT * FROM DEPT_TCL;


-- COMMIT 으로 명령어 반영하기
INSERT INTO DEPT_TCL VALUES(50,'NETWEORK','SEOUL');

UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 20;

DELETE FROM DEPT_TCL WHERE DEPTNO = 40;

SELECT * FROM DEPT_TCL;

COMMIT;


--토드와 sql * plus로 세션 알아보기

SELECT * FROM DEPT_TCL;

DELETE FROM DEPT_TCL
WHERE DEPTNO = 50;

SELECT * FROM DEPT_TCL;

COMMIT;

SELECT * FROM DEPT_TCL;

--토드와 SQL *PLUS로 LOCK 알아보기

SELECT * FROM DEPT_TCL;

UPDATE DEPT_TCL SET LOC='SEOUL'
WHERE DEPTNO = 30;

SELECT * FROM DEPT_TCL;

COMMIT;

SELECT * FROM DEPT_TCL;

